### PR TITLE
Add configurable default snd/rcv timeout

### PR DESCRIPTION
**Pull request by rbx**
- Add default send/receive timeout, configurable via `--channel-config` keys `sndTimeoutMs` and `rcvTimeoutMs`. Only affects default value (which is `-1` - no timeout - by default), when no explicit timeout argument is provided to Send/Receive.

### CODE REVIEW

**Review by dennisklein — COMMENTED** [review]
Would a `std::chrono::milliseconds` instead of `int` be feasible?

**Comment by rbx** [comment]
In principle yes. But since the other transfer timeouts are int i made this int also to be consistent. We can move all of them to chrono in one go. Or if it can be non-breaking I can add the full move as a commit here.

**Comment by dennisklein** [comment]
> Or if it can be non-breaking I can add the full move as a commit here.

Probably only as additional overloads.

**Comment by rbx** [comment]
I added another commit with some more zmq/shmem deduplications.

**Pull request merged**
