### PR TITLE
Allow sorting StateChange callbacks

### PR DESCRIPTION
**Pull request by ktf**

### CODE REVIEW

**Comment by ktf** [comment]
Is the thread sanitizer known to be broken?

**Comment by dennisklein** [comment]
> Is the thread sanitizer known to be broken?

yes, it was never green.

**Comment by ktf** [comment]
Can we have a release with this in? In principle it only affects the case in which you name your callback using a numeric prefix.

**Comment by rbx** [comment]
It is now available with v1.8.0. It also contains your previous contribution.

**Comment by ktf** [comment]
Thanks.

**Pull request merged**
