### PR TITLE
DeviceRunner: Extend lifetime of PluginManager beyond ProgOptions

### PR DESCRIPTION
**Pull request by rbx**
Solves #238.

### CODE REVIEW

**Comment by rbx** [comment]
Yes, `fConfig` and also `fDevice` ... switched to shared_ptr for both, now it works. I'll put this on WIP, want to see if it can be done without the shared_ptrs, but might have to wait with that until Monday.

**Comment by dennisklein** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- test/plugins/_plugin.cxx  2
         

Clones removed
==============
+ test/device/_config.cxx  -2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/FairRootGroup/FairMQ/pullRequest?prid=5305193&bid=17363814)

**Comment by dennisklein** [comment]
```diff
diff --git a/fairmq/PluginManager.cxx b/fairmq/PluginManager.cxx
index b1ffc0cf..61295ae7 100644
--- a/fairmq/PluginManager.cxx
+++ b/fairmq/PluginManager.cxx
@@ -28,6 +28,8 @@ using boost::optional;

 const std::string fair::mq::PluginManager::fgkLibPrefix = "FairMQPlugin_";

+std::vector<boost::dll::shared_library> fair::mq::PluginManager::fkDLLKeepAlive = std::vector<boost::dll::shared_library>();
+
 fair::mq::PluginManager::PluginManager()
     : fSearchPaths{}
     , fPluginFactories()
diff --git a/fairmq/PluginManager.h b/fairmq/PluginManager.h
index 085ac6b8..80feafb2 100644
--- a/fairmq/PluginManager.h
+++ b/fairmq/PluginManager.h
@@ -97,6 +97,7 @@ class PluginManager
         using fair::mq::tools::ToString;

         auto lib = shared_library{std::forward<Args>(args)...};
+        fkDLLKeepAlive.push_back(lib);

         fPluginFactories[pluginName] = import_alias<PluginFactory>(
             shared_library{lib},
@@ -117,6 +118,7 @@ class PluginManager

     static const std::string fgkLibPrefix;
     std::vector<boost::filesystem::path> fSearchPaths;
+    static std::vector<boost::dll::shared_library> fkDLLKeepAlive;
     std::map<std::string, std::function<PluginFactory>> fPluginFactories;
     std::unique_ptr<PluginServices> fPluginServices;
     std::map<std::string, std::unique_ptr<Plugin>> fPlugins;
```

Your idea, but applied only on the part that really needs longer lifetime. Yes, it is global state, but the `shared_library` objects truly represent global state - one cannot load the same shared library twice. Does this work for you as well?

**Comment by rbx** [comment]
Nice, that works. Updated the PR.

**Comment by rbx** [comment]
Test failures unrelated.

**Pull request merged**
