### PR TITLE
Bump asio to 1.18.0

### LINKED ISSUE #319: warning: declaration shadows a variable in namespace 'asio::ip' [-Wshadow]
```
In file included from /Users/alfaci/alfaci/workspace/FairRootGroup_FairMQ_PR-317/test/sdk/_topology.cxx:11:
In file included from /Users/alfaci/alfaci/workspace/FairRootGroup_FairMQ_PR-317/extern/asio/asio/include/asio.hpp:83:
In file included from /Users/alfaci/alfaci/workspace/FairRootGroup_FairMQ_PR-317/extern/asio/asio/include/asio/ip/basic_resolver.hpp:30:
In file included from /Users/alfaci/alfaci/workspace/FairRootGroup_FairMQ_PR-317/extern/asio/asio/include/asio/ip/basic_resolver_query.hpp:21:
In file included from /Users/alfaci/alfaci/workspace/FairRootGroup_FairMQ_PR-317/extern/asio/asio/include/asio/ip/resolver_query_base.hpp:19:
/Users/alfaci/alfaci/workspace/FairRootGroup_FairMQ_PR-317/extern/asio/asio/include/asio/ip/resolver_base.hpp:68:5: warning: declaration shadows a variable in namespace 'asio::ip' [-Wshadow]
    v4_mapped = ASIO_OS_DEF(AI_V4MAPPED),
    ^
/Users/alfaci/alfaci/workspace/FairRootGroup_FairMQ_PR-317/extern/asio/asio/include/asio/ip/address_v6.hpp:295:20: note: previous declaration is here
enum v4_mapped_t { v4_mapped };
                   ^
1 warning generated.
```

### PR DESCRIPTION
**Pull request by dennisklein**
~Fixes #319~

### CODE REVIEW

**Review by rbx — COMMENTED** [review]
The changes work for me (gcc 10.2 on linux).
I'm not familiar enough with Asio to understand how this fixes the warning. Is it a workaround, by using a different API path?

**Comment by dennisklein** [comment]
> The changes work for me (gcc 10.2 on linux).
> I'm not familiar enough with Asio to understand how this fixes the warning. Is it a workaround, by using a different API path?

The warning was in the asio code itself. So I upgraded to newer version which has fixed it.

**Comment by rbx** [comment]
sure, i mean i don't understand the changes in our code. The dispatch part looks like it's just taking a slightly different code path?

**Comment by dennisklein** [comment]
> sure, i mean i don't understand the changes in our code. The dispatch part looks like it's just taking a slightly different code path?

The changed are just adaptations to the new version.

**Review by rbx — APPROVED** [review]
Fixed warning or not, bump won't hurt.

**Pull request merged**
