### PR TITLE
Logger and warning fixes

### PR DESCRIPTION
**Pull request by dennisklein**

### CODE REVIEW

**Comment by rbx** [comment]
Should also bump the fairlogger requirement to v1.6.2, at least when SDK is built.

**Comment by rbx** [comment]
nevermind, i see what you did there

**Comment by rbx** [comment]
I would rather leave the definition of the `FAIR_NO_LOG`, so we don't force anyone using this header to also use `FAIR_LOG`.

**Comment by dennisklein** [comment]
> I would rather leave the definition of the `FAIR_NO_LOG` to the user, so we don't force anyone using this header to also use `FAIR_LOG`.

Done.

**Pull request merged**
