### PR TITLE
shm/zmq updates

### PR DESCRIPTION
**Pull request by rbx**
- Implement bulk callbacks for unmanaged regions:
Add a possibility to setup a region callback that is called with a number of buffer release notifications, instead of only one. This allows for a more efficient handling in some cases (shmem), where the release notifications are also transferred in bulk. The old callback signature is still supported.
- Unit test for unmanaged region release notifications.
- shmem: throw on bad_alloc (typically means that memory is full), device cmd option to disable it (retry if throwing is disabled).

All other commits contain non-functional changes(unless I missed something): refactoring/modernization, mostly for zmq/shmem:

- shmem: make header only (to make sure compiler doesn't miss anything useful). Transports are only compiled once, so this does not add any (noticeable) compile-time overhead.
- zmq: make header only too.
- cleanup includes.
- zmq: use namespaces.
- zmq: remove unnecessary global (static) state.
- replace exit(EXIT_FAILURE)s with exceptions.
- formatting.

### CODE REVIEW

**Comment by dennisklein** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- test/region/_region.cxx  1
         

Clones removed
==============
+ fairmq/FairMQChannel.h  -1
+ fairmq/FairMQDevice.h  -1
+ fairmq/zeromq/FairMQSocketZMQ.cxx  -2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/FairRootGroup/FairMQ/pullRequest?prid=5528599&bid=18120620)

**Comment by rbx** [comment]
Test failures unrelated.

**Comment by dennisklein** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- fairmq/shmem/TransportFactory.h  1
- fairmq/zeromq/TransportFactory.h  1
- test/region/_region.cxx  1
- fairmq/shmem/Socket.h  18
- fairmq/zeromq/Poller.h  13
- fairmq/zeromq/Socket.h  17
- fairmq/shmem/Poller.h  11
         

Clones removed
==============
+ fairmq/FairMQChannel.h  -1
+ fairmq/shmem/Message.h  -1
+ fairmq/FairMQDevice.h  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/FairRootGroup/FairMQ/pullRequest?prid=5528599&bid=18120620)

**Comment by dennisklein** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- fairmq/shmem/Poller.h  11
- fairmq/shmem/TransportFactory.h  1
- fairmq/zeromq/TransportFactory.h  1
- fairmq/zeromq/Poller.h  13
- test/region/_region.cxx  1
- fairmq/zeromq/Socket.h  17
- fairmq/shmem/Socket.h  18
         

Clones removed
==============
+ fairmq/FairMQDevice.h  -1
+ fairmq/shmem/Message.h  -1
+ fairmq/FairMQChannel.h  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/FairRootGroup/FairMQ/pullRequest?prid=5528599&bid=18120620)

**Pull request merged**
