### PR TITLE
Support static builds

### PR DESCRIPTION
**Pull request by dennisklein**
1. Support CMake variable [`BUILD_SHARED_LIBS`](https://cmake.org/cmake/help/v3.0/variable/BUILD_SHARED_LIBS.html) (triggered by #89).

2. Fix an ODR violation in the unity build regarding posix signal handling. @rbx Could this be related to the issue with the missed `SIGINT`? Strangely neither of the CI builds generate an error here, only get it with GCC 8.

---

Checklist:

* [x] Rebased against `dev` branch
* [x] My name is in the resp. CONTRIBUTORS/AUTHORS file
* [x] Followed [the seven rules of great commit messages](https://chris.beams.io/posts/git-commit/#seven-rules)

### CODE REVIEW

**Comment by rbx** [comment]
I'm not aware of any missed signals, what has been reported so far races in handling the signal. Is anyone using unity builds? The Monitor doesn't need to be part of FairMQ library, it is an independent executable. With errors such as ODR violation I would expect to see it either always fail or always happen to work. Cannot imagine how such an issue would contribute to signals being missed sometimes. But again I have never even seen such issues on our side.

**Comment by dennisklein** [comment]
> Is anyone using unity builds?

Yes, alfa-ci.

> The Monitor doesn't need to be part of FairMQ library, it is an independent executable. 

That is how I fixed it, `fairmq-shmmonitor` no longer depends on FairMQ.

**Comment by dennisklein** [comment]
> I'm not aware of any missed signals - what has been reported so far are races in signal handling. 

That is what I meant.

> With errors such as ODR violation I would expect to see it either always fail or always happen to work. Cannot imagine how such an issue would contribute to signals being missed sometimes.

Maybe some strange compiler bug. The facts, that the CI build uses unity build and should have seen the ODR violation, which it did not, and that code regarding the signal handling is affected, made me think this could be related to the observed races which we have not understood yet, haven't we?

**Comment by rbx** [comment]
Right. So far I have only seen the signal issues occur on my mac and as described in #83. Not sure if we have seen them on our test environment, or perhaps we did, but dismissed them as something else?

**Comment by rbx** [comment]
When reproducing #83 on my mac I did not use unity build, I don't think there's any way for the global in the Monitor to affect whatever I was running there, is there?

**Comment by dennisklein** [comment]
Alright, thx for clearing it up. I had to push again, noticed another mistake, didn't mean to delete the PIC setting.

Btw, the analog support for the `BUILD_SHARED_LIBS` flag I added to FairLogger and released it as `v1.3.0`. This also includes now your added mutex.

**Pull request merged**
